---

- name: playbook to deploy application on kubernetes
  hosts: all
  become: yes
  user: root
  


  tasks:
    - name: run below command
      shell: su ubuntu && kubectl apply -f deploy.yaml


    - name: run below command to deploy service
      shell: su ubuntu && kubectl deploy -f service.yaml    

